### ISSUE TITLE
Error with Set POE command

### ISSUE THREAD

**Issue by hroberts65616** [codeout/vscode-junos#16] opened 2022-07-25 19:05 UTC
Thank you for resolving Bug #15. That one is no longer reporting as a problem to me.

But I am now seeing that I have a line that says set poe interface ge-0/0/0 and it is telling me that ge-0/0/0 is not defined.

When I specifically make the command:
set interfaces interface-range CAMERA_POE member ge-0/0/0
It still reports it as not defined.  I was thinking it was because my original line is:
set interfaces interface-range CAMERA_POE member-range ge-0/0/0 to ge-0/0/3

If I set it to any other item except for all It tells me it is not defined.

Thanks,

**Comment by codeout** [comment] 2022-07-26 14:07
I'd like to clarify your problem. Let's say we have config below, do you mean the problem is that `ge-0/0/0` and `ge-0/0/1` are marked as "not defined" in `set protocols ospf ...` statements?

<img width="873" alt="image" src="https://user-images.githubusercontent.com/921696/181019387-49a37df2-ed3a-49ab-be31-53e4aa09b98f.png">

If so, it's difficult to resolve because we cannot theoritically determine if a referred interface is defined in config lines. It also depends on hardware configuration.

```
set interfaces interface-range foo member xe-0/0/*
# or
set interfaces interface-range foo member-range xe-0/0/0 to xe-0/1/0

# then, the line below is valid for QFX while invalid for smaller devices
set protocols ospf area 0.0.0.0 interface xe-0/0/16
```

Any ideas?

**Comment by codeout** [comment] 2022-07-26 14:17
However, we can expand `interface-range` statement into a full interface definition in special cases like:

- `member ge-0/0/0` ( no wildcard )
- `member-range ge-0/0/0 to ge-0/0/3` ( fixed FPC# and PIC# )

It could be an option to support these cases only.

**Comment by hroberts65616** [comment] 2022-07-26 14:33
I understand what you are saying.  I think the issue is that the command
"set poe interface"  Will not accept anything but all.

It does not like me using set poe interface ge-0/0/1.  The only time it did
not give me an "problem" was when I set it to set poe interface all

I hope that makes sense.

I think that would work in your example as well. if after interface it can
accept a valid port whether that be ge-... or xe- or et- or any other port
type

**Comment by codeout** [comment] 2022-07-26 14:44
Ah, I see. Something wrong with `set poe interface` statement. I'll take a look.
By the way, I haven't configured `set poe interface` in my life. Is that only for EX series?

**Comment by hroberts65616** [comment] 2022-07-26 14:52
Not necessarily, but I do use it alot on the EX's.

When I only want to turn on POE on one port.

Thanks

**Comment by codeout** [comment] 2022-07-26 14:54
Understood. Thanks!

**Comment by codeout** [comment] 2022-08-07 10:55
@hroberts65616 I noticed that current vscode-junos doesn't support `set poe ...` at all.

Is it possible to get netconf schema from your EX device to implement the poe syntax?
This plugin has pre-compiled syntax trees generated from netconf schema, so we need to get the schema and compile it.

## How to get netconf schema

Just in case you aren't familiar with netconf,

1. Temporarily configure netconf on your EX device:

```
set system services netconf ssh
```

2. Get netconf schema:

```
# on linux

cat > get-schema.xml <<EOS
<?xml version="1.0" encoding="UTF-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
  </capabilities>
</hello>
]]>]]>
<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <get-xnm-information>
    <type>xml-schema</type>
    <namespace>junos-configuration</namespace>
  </get-xnm-information>
</rpc>
]]>]]>
<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
  <close-session/>
</rpc>
EOS

ssh -Csp 830 [EX device hostname] netconf < get-schema.xml > ex.xsd
```

3. Rollback EX device

```
delete system services netconf
```

4. Send me the `ex.xsd`

Additionally, output of `show version` will  be much helpful.

Thanks.

**Comment by hroberts65616** [comment] 2022-08-11 22:19
Hello,

I have an EX3300 that is fresh out of the box that I can test this with.  I
am confused by the first part of this command.

I am SSHing into the switch and doing the set system services and then on
the ssh terminal I am typing on Linux?

Thanks,

**Comment by codeout** [comment] 2022-08-12 01:54
Hi,

> I have an EX3300 that is fresh out of the box that I can test this with.

Sounds nice. Thanks a lot for your cooperation.

> 1. Temporarily configure netconf on your EX device:

Please type on your EX switch.

> 2. Get netconf schema:

Please type on Linux server.

> 3. Rollback EX device

Please type on the switch again.

If you have any further questions, please let me know.

**Comment by hroberts65616** [comment] 2022-08-12 02:16
Ok I don't have a Linux server available to me.  I only have Windows.

**Comment by codeout** [comment] 2022-08-12 02:19
I see, I'll try on windows and send you other commands.

**Comment by codeout** [comment] 2022-08-12 04:11
Hi,

This works for me:

1. Create a text file ( `.\Desktop\get-schema.xml` for example ) and edit:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
  </capabilities>
</hello>
]]>]]>
<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <get-xnm-information>
    <type>xml-schema</type>
    <namespace>junos-configuration</namespace>
  </get-xnm-information>
</rpc>
]]>]]>
<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
  <close-session/>
</rpc>
```

2. Call netconf

```
PS C:\Users\koji> cat .\Desktop\get-schema.xml | ssh -Csp 830 192.168.0.73 netconf > ex.xsd
```

**Comment by dellhem** [comment] 2022-10-07 08:16
Hi,

This valid command is marked as an error:

![image](https://user-images.githubusercontent.com/6972495/194505793-c7f5dbfb-423e-4313-8fdb-ee0695a5cb3f.png)

`set protocols iccp peer 10.9.8.54 liveness-detection single-hop`

**Comment by codeout** [comment] 2022-11-02 02:46
Hi @hroberts65616, any updates on ex.xsd?

**Comment by codeout** [comment] 2023-12-14 13:33
Closing due to inactivity. Please feel free to reopen it if you need.

**Closed as completed by codeout** 2023-12-14 13:33 UTC
